### ISSUE TITLE
request to add option for solid fill

### ISSUE THREAD

**Issue by TheRealAaronPrince** [Timardo/LT-3D-Importer#4]
I've got a model that I want to make rather large as a statue, as well as have it be on the 32 resolution option, but I keep running into the 2048 tiles per block issue. I was wondering if you'd add the option for a solid fill on models to allow for higher resolutions without going over the tile limit

**Comment by Timardo** [comment]
Solid fill is a feature I will never add as it is very difficult to determine what exactly should be filled just by code and all in all does not provide much to the end user. Textured models with solid fill would have even higher tile count as hollow ones and nontextured models made out of one color will have at best just a little less tiles.
The tile limit of 2048 tiles per block is configurable in the LittleTiles config file. If you are playing on singleplayer or a server that you have access to, you can change this value to whatever value you want. This option is in the littletiles.json config file under maxAllowedDensity.
